export const USER_HISTORY_EVENTS = [
  { value: 'ACCOUNT_REGISTERED', label: 'Conta registrada' },
  { value: 'ACCOUNT_PAYMENT_LINK_GENERATED', label: 'Link de pagamento gerado' },
  { value: 'ACCOUNT_PLAN_LISTED', label: 'Planos listados' },
  { value: 'ACCOUNT_SIGNATURE_UPDATED', label: 'Assinatura da conta atualizada' },
  { value: 'USER_STATUS_CHANGED', label: 'Status do usuário alterado' },
  { value: 'USER_ROULLETE_SIGNATURE_UPDATED', label: 'Assinatura da roleta do usuário atualizada' },
  { value: 'USER_METRICS_VIEWED', label: 'Métricas do usuário visualizadas' },
  { value: 'USER_LIST_VIEWED', label: 'Lista de usuários visualizada' },
  { value: 'USER_INVITE_CREATED', label: 'Convite criado' },
  { value: 'USER_INVITE_ACCEPTED', label: 'Convite aceito' },
  { value: 'USER_WHATSAPP_SESSION_VIEWED', label: 'Sessão do WhatsApp do usuário visualizada' },
  { value: 'PROPERTY_CREATED', label: 'Imóvel criado' },
  { value: 'PROPERTY_LIST_VIEWED', label: 'Lista de imóveis visualizada' },
  { value: 'PROPERTY_MEDIA_UPLOADED', label: 'Mídia do imóvel enviada' },
  { value: 'PROPERTY_MEDIA_DELETED', label: 'Mídia do imóvel deletada' },
  { value: 'PROPERTY_MEDIA_ORDER_UPDATED', label: 'Ordem das mídias do imóvel atualizada' },
  { value: 'PROPERTY_CATCHER_REMOVED', label: 'Captador removido do imóvel' },
  { value: 'PROPERTY_FEATURE_CREATED', label: 'Característica do imóvel criada' },
  { value: 'PROPERTY_FEATURE_UPDATED', label: 'Característica do imóvel atualizada' },
  { value: 'PROPERTY_FEATURE_LIST_VIEWED', label: 'Lista de características visualizada' },
  { value: 'PROPERTY_BUILDER_CREATED', label: 'Construtora criada' },
  { value: 'PROPERTY_BUILDER_UPDATED', label: 'Construtora atualizada' },
  { value: 'PROPERTY_BUILDER_DELETED', label: 'Construtora deletada' },
  { value: 'PROPERTY_BUILDER_LIST_VIEWED', label: 'Lista de construtoras visualizada' },
  { value: 'CONDOMINIUM_LIST_VIEWED', label: 'Lista de condomínios visualizada' },
  { value: 'CONDOMINIUM_CREATED', label: 'Condomínio criado' },
  { value: 'CONDOMINIUM_DELETED', label: 'Condomínio deletado' },
  { value: 'CONDOMINIUM_UPDATED', label: 'Condomínio atualizado' },
  { value: 'SECONDARY_DISTRICT_CREATED', label: 'Bairro secundário criado' },
  { value: 'SECONDARY_DISTRICT_UPDATED', label: 'Bairro secundário atualizado' },
  { value: 'SECONDARY_DISTRICT_DELETED', label: 'Bairro secundário deletado' },
  { value: 'SECONDARY_DISTRICT_LIST_VIEWED', label: 'Lista de bairros secundários visualizada' },
  { value: 'APPOINTMENT_CREATED', label: 'Agendamento criado' },
  { value: 'APPOINTMENT_UPDATED', label: 'Agendamento atualizado' },
  { value: 'APPOINTMENT_DELETED', label: 'Agendamento deletado' },
  { value: 'APPOINTMENT_LIST_VIEWED', label: 'Lista de agendamentos visualizada' },
  { value: 'TASK_CREATED', label: 'Tarefa criada' },
  { value: 'TASK_UPDATED', label: 'Tarefa atualizada' },
  { value: 'TASK_DELETED', label: 'Tarefa deletada' },
  { value: 'TASK_COMPLETED', label: 'Tarefa concluída' },
  { value: 'TASK_LIST_VIEWED', label: 'Lista de tarefas visualizada' },
  { value: 'TASK_TYPE_LIST_VIEWED', label: 'Lista de tipos de tarefas visualizada' },
  { value: 'LEAD_CREATED', label: 'Lead criado' },
  { value: 'LEAD_UPDATED', label: 'Lead atualizado' },
  { value: 'LEAD_LIST_VIEWED', label: 'Lista de leads visualizada' },
  { value: 'LEAD_FUNNEL_STEP_CHANGED', label: 'Etapa do funil do lead alterada' },
  { value: 'LEAD_CREDIT_ANALYSE_CREATED', label: 'Análise de crédito do lead criada' },
  { value: 'PROPERTY_VISIT_LIST_VIEWED', label: 'Lista de visitas a imóveis visualizada' },
  { value: 'TEAM_CREATED', label: 'Equipe criada' },
  { value: 'TEAM_DELETED', label: 'Equipe deletada' },
  { value: 'TEAM_LIST_VIEWED', label: 'Lista de equipes visualizada' },
  { value: 'TEAM_MEMBERS_VIEWED', label: 'Membros da equipe visualizados' },
  { value: 'TEAM_MEMBER_ADDED', label: 'Membro da equipe adicionado' },
  { value: 'TEAM_MEMBER_REMOVED', label: 'Membro da equipe removido' },
  { value: 'TEAM_UPDATED', label: 'Equipe atualizada' },
];
