import React, { useEffect, useMemo, useState } from 'react';
import { Plus, Trash2 } from 'lucide-react';

import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Switch } from '@/components/ui/switch';
import { Textarea } from '@/components/ui/textarea';
import { useToast } from '@/hooks/use-toast';
import {
  DEFAULT_STATUS_IDS,
  getAll as getStatuses,
  saveStatuses,
  slugify as slugifyId,
} from '@/features/imoveis/state/statusRegistry';
import { PropertyStatus } from '@/types/imovel';
import { cn } from '@/lib/utils';

interface StatusModalProps {
  open: boolean;
  onClose: () => void;
  onChange?: (statuses: PropertyStatus[]) => void;
}

interface StatusDraft extends PropertyStatus {
  _tempId: string;
  _isDefault?: boolean;
  _autoGeneratedId?: boolean;
}

const DEFAULT_NEW_COLOR = '#2563eb';

function createTempId(prefix: string): string {
  return `${prefix}-${Math.random().toString(36).slice(2, 10)}`;
}

function toDraft(status: PropertyStatus, isDefault: boolean): StatusDraft {
  return {
    ...status,
    _tempId: status.id || createTempId('status'),
    _isDefault: isDefault,
    _autoGeneratedId: false,
  };
}

export function StatusModal({ open, onClose, onChange }: StatusModalProps) {
  const { toast } = useToast();
  const [statuses, setStatuses] = useState<StatusDraft[]>([]);
  const [hasChanges, setHasChanges] = useState(false);

  useEffect(() => {
    if (!open) {
      return;
    }

    const loaded = getStatuses().map(status =>
      toDraft(status, DEFAULT_STATUS_IDS.has(status.id)),
    );

    setStatuses(loaded);
    setHasChanges(false);
  }, [open]);

  const sortedStatuses = useMemo(() => {
    return [...statuses].sort((a, b) => {
      if (a.order === b.order) {
        return a.label.localeCompare(b.label);
      }
      return a.order - b.order;
    });
  }, [statuses]);

  const handleAddStatus = () => {
    const nextOrder = statuses.length ? Math.max(...statuses.map(s => s.order)) + 1 : 1;
    const baseSlug = slugifyId(`novo-status-${statuses.length + 1}`) || createTempId('status');
    const uniqueSlug = ensureUniqueSlug(baseSlug, statuses);

    setStatuses(prev => [
      ...prev,
      {
        id: uniqueSlug,
        label: '',
        color: DEFAULT_NEW_COLOR,
        description: '',
        isActive: true,
        order: nextOrder,
        _tempId: createTempId('status'),
        _isDefault: false,
        _autoGeneratedId: true,
      },
    ]);
    setHasChanges(true);
  };

  const handleRemoveStatus = (index: number) => {
    setStatuses(prev => prev.filter((_, itemIndex) => itemIndex !== index));
    setHasChanges(true);
    toast({
      title: 'Status removido',
      description: 'O status será excluído após salvar as alterações.',
      variant: 'warning',
    });
  };

  const updateStatus = (index: number, patch: Partial<StatusDraft>) => {
    setStatuses(prev => {
      const next = [...prev];
      next[index] = {
        ...next[index],
        ...patch,
      };
      return next;
    });
    setHasChanges(true);
  };

  const handleLabelChange = (index: number, value: string) => {
    setStatuses(prev => {
      const next = [...prev];
      const draft = { ...next[index], label: value };
      if (draft._autoGeneratedId) {
        draft.id = slugifyId(value || draft.id || createTempId('status'));
      }
      next[index] = draft;
      return next;
    });
    setHasChanges(true);
  };

  const handleIdChange = (index: number, value: string) => {
    const sanitized = value.replace(/[^a-zA-Z0-9-_]/g, '-');
    updateStatus(index, {
      id: sanitized,
      _autoGeneratedId: false,
    });
  };

  const handleIdBlur = (index: number) => {
    setStatuses(prev => {
      const next = [...prev];
      const current = next[index];
      const slug = slugifyId(current.id || current.label || `status-${index + 1}`);
      next[index] = {
        ...current,
        id: slug || `status-${index + 1}`,
      };
      return next;
    });
    setHasChanges(true);
  };

  const handleSave = () => {
    if (!statuses.length) {
      toast({
        title: 'Inclua ao menos um status',
        description: 'Adicione um status para continuar.',
        variant: 'danger',
      });
      return;
    }

    const normalized: PropertyStatus[] = [];
    const slugs = new Set<string>();

    for (let index = 0; index < statuses.length; index += 1) {
      const draft = statuses[index];
      const label = draft.label.trim();

      if (!label) {
        toast({
          title: 'Informe o rótulo',
          description: 'Todos os statuses precisam de um rótulo.',
          variant: 'danger',
        });
        return;
      }

      const slug = slugifyId(draft.id || label);
      if (!slug) {
        toast({
          title: 'Slug inválido',
          description: 'O identificador deve conter letras ou números.',
          variant: 'danger',
        });
        return;
      }

      if (slugs.has(slug)) {
        toast({
          title: 'Slug duplicado',
          description: `O identificador “${slug}” já está sendo utilizado.`,
          variant: 'danger',
        });
        return;
      }

      slugs.add(slug);

      const orderValue = Number.isFinite(draft.order) ? draft.order : index + 1;

      normalized.push({
        id: slug,
        label,
        color: draft.color || DEFAULT_NEW_COLOR,
        description: draft.description?.trim() ?? '',
        isActive: Boolean(draft.isActive),
        order: Number(orderValue),
      });
    }

    const saved = saveStatuses(normalized);
    setStatuses(saved.map(status => toDraft(status, DEFAULT_STATUS_IDS.has(status.id))));
    setHasChanges(false);
    toast({
      title: 'Statuses atualizados',
      description: 'As opções foram salvas com sucesso.',
      variant: 'success',
    });
    onChange?.(saved);
  };

  const handleOpenChange = (nextOpen: boolean) => {
    if (!nextOpen) {
      onClose();
    }
  };

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent className="sm:max-w-3xl">
        <DialogHeader>
          <DialogTitle>Gerenciar status do imóvel</DialogTitle>
          <DialogDescription>
            Crie ou personalize os status disponíveis no formulário. Essas alterações são salvas apenas no seu navegador.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-muted-foreground">
                Defina identificadores únicos, cores e descrições para organizar melhor o fluxo de trabalho da equipe.
              </p>
            </div>
            <Button
              type="button"
              variant="outline"
              onClick={handleAddStatus}
              className="rounded-xl"
            >
              <Plus className="mr-2 h-4 w-4" /> Novo status
            </Button>
          </div>

          <ScrollArea className="max-h-[28rem] pr-2">
            <div className="space-y-4">
              {sortedStatuses.map(draft => {
                const index = statuses.findIndex(item => item._tempId === draft._tempId);
                const isDefault = draft._isDefault;

                return (
                  <div
                    key={draft._tempId}
                    className="rounded-2xl border border-border bg-muted/10 p-4"
                  >
                    <div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between">
                      <div className="flex-1 space-y-4">
                        <div className="grid gap-4 md:grid-cols-2">
                          <div className="space-y-2">
                            <Label htmlFor={`status-label-${draft._tempId}`}>Rótulo</Label>
                            <Input
                              id={`status-label-${draft._tempId}`}
                              placeholder="Ex.: Em negociação"
                              value={draft.label}
                              onChange={event => handleLabelChange(index, event.target.value)}
                            />
                          </div>
                          <div className="space-y-2">
                            <Label htmlFor={`status-id-${draft._tempId}`}>
                              Identificador
                            </Label>
                            <Input
                              id={`status-id-${draft._tempId}`}
                              placeholder="slug-do-status"
                              value={draft.id}
                              onChange={event => handleIdChange(index, event.target.value)}
                              onBlur={() => handleIdBlur(index)}
                              disabled={isDefault}
                            />
                            <p className="text-xs text-muted-foreground">
                              Use letras minúsculas, números ou hífens. Esse valor deve ser único.
                            </p>
                          </div>
                        </div>

                        <div className="grid gap-4 md:grid-cols-[minmax(0,140px)_1fr]">
                          <div className="space-y-2">
                            <Label htmlFor={`status-color-${draft._tempId}`}>Cor</Label>
                            <div className="flex items-center gap-3">
                              <Input
                                id={`status-color-${draft._tempId}`}
                                type="color"
                                value={draft.color || DEFAULT_NEW_COLOR}
                                onChange={event =>
                                  updateStatus(index, { color: event.target.value })
                                }
                                className="h-10 w-16 rounded-xl border border-border px-1 py-1"
                              />
                              <span className="text-sm font-medium text-muted-foreground uppercase">
                                {(draft.color || DEFAULT_NEW_COLOR).toUpperCase()}
                              </span>
                            </div>
                          </div>
                          <div className="space-y-2">
                            <Label htmlFor={`status-description-${draft._tempId}`}>
                              Descrição (opcional)
                            </Label>
                            <Textarea
                              id={`status-description-${draft._tempId}`}
                              rows={2}
                              value={draft.description || ''}
                              onChange={event =>
                                updateStatus(index, { description: event.target.value })
                              }
                              placeholder="Explique quando esse status deve ser usado."
                            />
                          </div>
                        </div>
                      </div>

                      <div className="flex w-full flex-col justify-between gap-4 md:w-48">
                        <div className="space-y-2">
                          <Label htmlFor={`status-order-${draft._tempId}`}>Ordem</Label>
                          <Input
                            id={`status-order-${draft._tempId}`}
                            type="number"
                            min={1}
                            value={draft.order}
                            onChange={event =>
                              updateStatus(index, { order: Number(event.target.value) || 1 })
                            }
                          />
                        </div>
                        <div className="flex items-center justify-between rounded-xl border border-border px-3 py-2">
                          <div className="space-y-1">
                            <Label className="text-xs font-medium">Ativo</Label>
                            <p className="text-xs text-muted-foreground">
                              Status disponível no seletor.
                            </p>
                          </div>
                          <Switch
                            checked={draft.isActive}
                            onCheckedChange={checked => updateStatus(index, { isActive: checked })}
                          />
                        </div>

                        <div className="flex items-center justify-end">
                          <Button
                            type="button"
                            variant="ghost"
                            size="icon"
                            onClick={() => handleRemoveStatus(index)}
                            className={cn(
                              'rounded-xl text-red-500 hover:bg-red-50 hover:text-red-600',
                              isDefault && 'invisible pointer-events-none opacity-0',
                            )}
                          >
                            <Trash2 className="h-4 w-4" />
                          </Button>
                        </div>
                      </div>
                    </div>

                    {isDefault && (
                      <p className="mt-3 text-xs text-muted-foreground">
                        Este é um status padrão e não pode ter o identificador removido. Você ainda pode atualizar rótulo, cor e descrição.
                      </p>
                    )}
                  </div>
                );
              })}
            </div>
          </ScrollArea>
        </div>

        <DialogFooter className="mt-4">
          <Button type="button" variant="outline" onClick={onClose} className="rounded-xl">
            Cancelar
          </Button>
          <Button
            type="button"
            onClick={handleSave}
            disabled={!hasChanges}
            className="rounded-xl"
          >
            Salvar alterações
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

function ensureUniqueSlug(baseSlug: string, statuses: StatusDraft[]): string {
  const existingIds = new Set(statuses.map(status => status.id));
  if (!existingIds.has(baseSlug)) {
    return baseSlug;
  }

  let attempt = baseSlug;
  let index = 1;
  while (existingIds.has(attempt)) {
    attempt = `${baseSlug}-${index}`;
    index += 1;
  }

  return attempt;
}
