import { NavItem } from '@/shared/types';
import {
  Bell,
  BellDot,
  Building,
  Building2,
  Calendar,
  CreditCard,
  FileDown,
  House,
  Plug,
  Settings2,
  Share2,
  ShieldUser,
  Shuffle,
  TrendingUp,
  Users,
  Users2,
} from 'lucide-react';

export const navItems: NavItem[] = [
  {
    exact: true,
    title: 'Home',
    href: '/dashboard',
    icon: House,
    permissionCode: ['1000'],
    description: 'Acompanhe indicadores e resumos da operação em um só lugar.',
  },
  {
    title: 'Negociação',
    href: '/dashboard/sales',
    icon: TrendingUp,
    permissionCode: ['1200'],
    description: '',
  },
  {
    title: 'Agenda',
    href: '/dashboard/calendar',
    icon: Calendar,
    permissionCode: ['1300', '1301'],
    description: 'Organize compromissos e visualize sua agenda.',
  },
  {
    title: 'Imóveis',
    href: '/dashboard/properties',
    icon: Building,
    permissionCode: ['2500'],
    description: 'Cadastre, visualize e gerencie os imóveis da imobiliária.',
  },
  {
    title: 'Usuários',
    href: '/dashboard/users',
    icon: Users,
    permissionCode: ['1400'],
    description: 'Gerencie os usuários internos da sua imobiliária, como corretores e membros da equipe',
  },
  {
    title: 'Distribuição',
    href: '/dashboard/distribution',
    icon: Share2,
    permissionCode: ['1600'],
    description: 'Gerencie a distribuição de leads',
  },
  {
    title: 'Gestão de Acessos',
    href: '/dashboard/access-control',
    icon: ShieldUser,
    permissionCode: ['1700'],
    description: 'Configure permissões para diferentes funções de usuários',
  },
  {
    title: 'Gestão Roletão',
    href: '/dashboard/manage-rotary-leads',
    icon: Shuffle,
    permissionCode: ['1800'],
    description: 'Configurações do bolão de lead',
  },
  {
    title: 'Gestão API',
    href: '/dashboard/manage-api',
    icon: Plug,
    permissionCode: ['1900'],
    description: 'Configurações de webhooks e integrações externas',
  },
  {
    title: 'Pagamentos',
    href: '/dashboard/payments',
    icon: CreditCard,
    permissionCode: ['2000'],
    description: 'Gerencie planos, faturas, métodos de pagamento e dados fiscais da sua conta.',
  },
  {
    title: 'Gestão de Relatórios',
    href: '/dashboard/manage-reports',
    icon: FileDown,
    permissionCode: ['2100'],
    description: 'Visualize e exporte relatórios detalhados',
  },
  {
    title: 'Gestão de Imóveis',
    href: '/dashboard/manage-properties',
    icon: Building2,
    permissionCode: ['2200'],
    description: 'Gerencie características, tipos e outras configurações relacionadas aos imóveis',
  },
  {
    title: 'Gestão de Condomínios',
    href: '/dashboard/manage-condominiums',
    icon: Building,
    permissionCode: ['2300'],
    description: 'Gerencie os condomínios vinculados aos imóveis da sua imobiliária',
  },
  {
    title: 'Indicadores de Leads',
    href: '/dashboard/manage-leads',
    icon: Users2,
    permissionCode: ['1500'],
    description: 'Gerencie configurações relacionadas aos leads, como arquivamentos e afins',
  },
];

export const sadmNavItems: NavItem[] = [
  { exact: true, title: 'Home', href: '/sadm-dashboard', icon: House, permissionCode: [], description: '' },
  {
    title: 'Clientes',
    href: '/sadm-dashboard/clients',
    icon: Users,
    permissionCode: [],
    description: 'Visualize e gerencie os clientes da plataforma',
  },
  {
    title: 'Gestão de Acessos',
    href: '/sadm-dashboard/access-control',
    icon: ShieldUser,
    permissionCode: [],
    description: 'Configure permissões para diferentes funções de usuários',
  },
  {
    title: 'Gestão de Planos',
    href: '/sadm-dashboard/plans-control',
    icon: Settings2,
    permissionCode: [],
    description: 'Configure os planos atuais da plataforma',
  },
  {
    title: 'Notificações',
    href: '/sadm-dashboard/manage-notifications',
    icon: Bell,
    permissionCode: [],
    description: 'Configure as notificações',
  },
  {
    title: 'Lembretes',
    href: '/sadm-dashboard/notification-reminders',
    icon: BellDot,
    permissionCode: [],
    description: 'Configure os lembretes automáticos',
  },
];
